spring.application.name=demo

# R2DBC conexión reactiva
spring.r2dbc.url=r2dbc:sqlserver://localhost:1433/springboot
spring.r2dbc.username=sa
spring.r2dbc.password=123456aA*

# Inicialización de scripts (opcional)
spring.sql.init.mode=always

# Logs
logging.level.org.springframework.r2dbc=DEBUG
